### ISSUE TITLE
Problem cloning foxyclient-php-example.git

### ISSUE THREAD

**Issue by nickweavers** [FoxyCart/foxyclient-php-example#6]
I have an ssh key entered in my github account and have checked that it authenticates me from my Pc my issuing 
`ssh -T git@github.com` to which the response is 
```
   Hi nickweavers! You've successfully authenticated, but GitHub does not provide shell access.
```
but when I issue
`git clone git@github.com:nickweavers/foxyclient-php-example` I get
```
     Cloning into foxyclient-php-example...
     ERROR: Repository not found.
     fatal: Could not read from remote repository.
     Please make sure you have the correct access rights
     and the repository exists.
```
What am I doing wrong?

Thanks,
Nick

**Comment by adamjudd** [comment]
@nickweavers,

Sorry to hear you're having trouble cloning the repo. From the URL you're attempting to clone, it looks like you're trying to clone a fork of our repo. It doesn't look like you've actually forked it yet though, which is why it's reporting the repository can't be found. If you first fork our repo, you should then be able to clone it like you're trying. Alternatively, you can just clone our own repo like this:

`git clone git@github.com:FoxyCart/foxyclient-php-example.git`

I hope that helps!

**Comment by nickweavers** [comment]
Perfect, 
Many thanks. 

    On Monday, 6 May 2019, 02:06:32 BST, Adam Judd <notifications@github.com> wrote:  
 
 
@nickweavers,

Sorry to hear you're having trouble cloning the repo. From the URL you're attempting to clone, it looks like you're trying to clone a fork of our repo. It doesn't look like you've actually forked it yet though, which is why it's reporting the repository can't be found. If you first fork our repo, you should then be able to clone it like you're trying. Alternatively, you can just clone our own repo like this:

git clone git@github.com:FoxyCart/foxyclient-php-example.git

I hope that helps!
